name: BMS Movie Checker

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq fonts-liberation libappindicator3-1 \
            libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 \
            libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils

      - name: Install Chrome for Testing
        run: |
          # Get latest stable version
          VERSION_DATA=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json")
          CHROME_VERSION=$(echo "$VERSION_DATA" | jq -r '.channels.Stable.version')
          
          # Download and install Chrome
          wget -q -O chrome.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chrome-linux64.zip"
          unzip chrome.zip
          sudo mv chrome-linux64/chrome /usr/local/bin/google-chrome
          sudo ln -s /usr/local/bin/google-chrome /usr/bin/google-chrome
          rm -rf chrome.zip chrome-linux64

      - name: Install matching ChromeDriver
        run: |
          # Get the same version for ChromeDriver
          VERSION_DATA=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json")
          CHROMEDRIVER_VERSION=$(echo "$VERSION_DATA" | jq -r '.channels.Stable.version')
          
          # Download and install ChromeDriver
          wget -q -O chromedriver.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver.zip chromedriver-linux64

      - name: Verify installations
        run: |
          echo "Chrome version: $(google-chrome --version)"
          echo "ChromeDriver version: $(chromedriver --version)"
          ls -la /usr/local/bin/chromedriver

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver==3.5.3 selenium==4.15.2 python-dotenv beautifulsoup4

      - name: Run checker
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MOVIE_NAME: ${{ secrets.MOVIE_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TIMEZONE: "Asia/Colombo"
        run: python checker.py