name: BMS Movie Checker

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:         # manual trigger

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip fonts-liberation libappindicator3-1 libatk-bridge2.0-0 libcups2 \
            libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils

      - name: Install Google Chrome Stable
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        run: |
          # Get Chrome version and extract major version number
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)
          echo "Detected Chrome version: $CHROME_VERSION"
          echo "Using Chrome major version: $CHROME_MAJOR"

          # Try to get matching ChromeDriver version
          echo "Fetching ChromeDriver version..."
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR")
          
          # Verify version was obtained
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to get ChromeDriver version"
            exit 1
          fi
          
          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Download and install ChromeDriver
          echo "Downloading ChromeDriver..."
          wget -nv --show-progress -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          
          echo "Installing ChromeDriver..."
          unzip -o chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verify installation
          echo "ChromeDriver version: $(chromedriver --version)"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checker
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MOVIE_NAME: ${{ secrets.MOVIE_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TIMEZONE: "Asia/Colombo"
        run: |
          echo "Starting movie check..."
          python checker.py
          echo "Check completed"