name: BMS Movie Checker

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq fonts-liberation libappindicator3-1 \
            libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 \
            libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils

      - name: Install Chrome and ChromeDriver (precise version matching)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'  # Gets the latest stable version
          chromedriver: true       # Auto-installs matching ChromeDriver

      - name: Verify installations
        run: |
          echo "Chrome version: $(google-chrome --version)"
          echo "ChromeDriver version: $(chromedriver --version)"
          google-chrome --version > chrome_version.txt
          chromedriver --version > chromedriver_version.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver==3.5.3 selenium==4.15.2 python-dotenv beautifulsoup4

      - name: Run checker
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MOVIE_NAME: ${{ secrets.MOVIE_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TIMEZONE: "Asia/Colombo"
        run: |
          echo "Starting movie check..."
          python checker.py
          echo "Check completed"