name: BMS Movie Checker

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:         # manual trigger

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq fonts-liberation libappindicator3-1 \
            libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 \
            libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        run: |
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Detected Chrome version: $CHROME_VERSION"

          # Get matching ChromeDriver version from new endpoint
          echo "Fetching compatible ChromeDriver version..."
          VERSION_DATA=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json")
          CHROMEDRIVER_VERSION=$(echo "$VERSION_DATA" | jq -r '.channels.Stable.version')
          
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Error: Could not determine ChromeDriver version"
            exit 1
          fi
          
          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Download and install
          echo "Downloading ChromeDriver..."
          DOWNLOAD_URL=$(echo "$VERSION_DATA" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -nv --show-progress -N "$DOWNLOAD_URL" -O chromedriver.zip
          
          echo "Installing ChromeDriver..."
          unzip -o chromedriver.zip -d chromedriver-temp
          sudo mv -f chromedriver-temp/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver.zip chromedriver-temp
          
          echo "Verifying installation..."
          chromedriver --version

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, installing default packages"
            pip install selenium python-dotenv beautifulsoup4
          fi

      - name: Run checker
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MOVIE_NAME: ${{ secrets.MOVIE_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TIMEZONE: "Asia/Colombo"
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"
        run: |
          echo "Starting movie check at $(date)"
          python checker.py || echo "Checker script failed"
          echo "Check completed at $(date)"